
version: 2

models:
  - name: stg_sncf_disruptions
    description: "A starter dbt model"
    columns:
      - name: id
        data_tests:
          - not_null
      - name: ingestion_ts
        data_tests:
          - not_null
      - name: status
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['active', 'past', 'future']

